// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xfgbbvahadkbxyiwwmsk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhmZ2JidmFoYWRrYnh5aXd3bXNrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2MjI0NDksImV4cCI6MjA2NzE5ODQ0OX0.B-DFG0n7a_XesrQX5UrR_Yr5pKwSS_kjJtKSImZeH5M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});